--- #YAML:1.3
name: CAE-Nastran-Nasmod
abstract: basic access to nastran models
version: [% version %]
author:
  - Alexander Vogel <avoge@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test: 0
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://prozesskraft.de
  bugtracker: https://github.com/alexvogel/cae-nastran-nasmod/issues
  repository: https://github.com/alexvogel/cae-nastran-nasmod
  git: git://github.com/alexvogel/cae-nastran-nasmod.git
  twitter: https://twitter.com/prozesskraft
keywords
  - CA
  - CAE
  - FEA
  - FEM
  - nastran
  - Finite-Elements
  - perl
  - CAE-Automation
  - CAE-Automatisierung
